max_cycle = 999
n_replica = 50
n_parallel = 50
centering = true
centering_selection = "centering"
working_dir = "./."

simulator = "gromacs"
cmd_mpi = "mpirun -np 50 "
cmd_serial = "gmx_mpi mdrun -ntomp 48"
cmd_parallel = "gmx_mpi mdrun -ntomp 48"
structure = "../LUF5833/input.gro"
topology = "../LUF5833/topol.top"
mdconf = "../LUF5833/mdpacs.mdp"
index_file = "../LUF5833/index.ndx"
trajectory_extension = ".xtc"

type = "dissociation"
threshold = 100
skip_frame = 5
analyzer = "gromacs"
selection1 = "Protein"
selection2 = "MOL"

rmmol = true
keep_selection = "Protein_MOL_Na+_K+_Cl-"
rmfile = true

cmd_gmx = "gmx"
