max_cycle = 50
n_replica = 50
n_parallel = 4
centering = true
working_dir = "./."
simulator = "gromacs"
cmd_gmx = "gmx_mpi"
cmd_mpi = "mpirun -np 4"
cmd_serial = "gmx_mpi mdrun -ntomp 7"
cmd_parallel = "gmx_mpi mdrun -ntomp 7"
structure = "input.gro"
reference = "input.tpr"
topology = "topol.top"
mdconf = "pacs.mdp"
index_file = "index.ndx"
trajectory_extension = ".xtc"

type = "rmsd"
threshold = 10
analyzer = "gromacs"
selection1 = "Backbone"
selection2 = "Backbone"

rmmol = true
keep_selection = "non-Water"
rmfile = true
